theme: jekyll-theme-hacker
title: Samip5's Github Page
name: Sami Mäntysaari
author: samip5
lang: en-US
google_analytics: UA-44228883-4
show_downloads: false
plugins:
  - jekyll-feed
footer-links:
  facebook: smantysaari
  github: samip5
  instagram: samip537
  linkedin: samip537
  rss: yes
  twitter: samip537