theme: jekyll-theme-hacker
title: Skyler Mäntysaari's (samip5) Github Page
name: Skyler Mäntysaari
author: samip5
lang: en-US
google_analytics: UA-44228883-4
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
footer-links:
  facebook: smantysaari
  github: samip5
  instagram: samip537
  linkedin: samip537
  rss: yes
  twitter: mantysaaris
